version: "3.9"
services:
  #---------------MAIN SERVICES--------------#
  catalog-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - kong-net
      - service-net
    volumes:
      - ./catalog-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
  order-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    expose:
      - 3000
    networks:
      - kong-net
      - service-net
    volumes:
      - ./order-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
  user-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    expose:
      - 3000
    networks:
      - kong-net
      - service-net
    volumes:
      - ./user-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
  mailer-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./workers/mailer
      dockerfile: Dockerfile
    networks:
      - service-net
    volumes:
      - ./workers/mailer:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
  
  #--------------------- GATEWAY ---------------------#
  kongdb:
    profiles:
      - litedev
      - dev
    image: docker.io/bitnami/postgresql:13
    networks:
      - kong-net
    volumes:
      - kongdb-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${KONG_DB_USER:-kong}
      - POSTGRESQL_PASSWORD=${KONG_DB_PASSWORD:-123456}
      - POSTGRESQL_DATABASE=${KONG_DB_DBNAME:-kong}
  kong:
    profiles:
      - litedev
      - dev
    depends_on:
      - kongdb
    image: docker.io/bitnami/kong:2.8.1
    ports:
      - 8000:8000
      - 8443:8443
    expose:
      - 8001
    networks:
      - kong-net
    environment:
      - KONG_MIGRATE=yes
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_DB_HOST:-kongdb}
      - KONG_PG_USER=${KONG_DB_USER:-kong}
      - KONG_PG_PASSWORD=${KONG_DB_PASSWORD:-123456}
  konga:
    profiles:
      - dev
    depends_on:
      - kong
    image: pantsel/konga:latest
    ports:
      - 1337:1337
    networks:
      - kong-net
    volumes:
      - konga-data:/app/kongadata
    environment:
      KONGA_LOG_LEVEL: ${KONGA_LOG_LEVEL:-debug}
      NODE_ENV: ${NODE_ENV:-development}

networks:
  kong-net:
    external: false
    driver: bridge
  service-net:
    external: false
    driver: bridge

volumes:
  kongdb-data:
    driver: local
  konga-data:
    driver: local