version: "3.9"
services:
  #---------------MAIN SERVICES--------------#
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./catalog-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    expose:
      - 3001
    volumes:
      - ./order-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3001
  user-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    expose:
      - 3001
    volumes:
      - ./user-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3001