version: "3.9"
services:
  #---------------MAIN SERVICES--------------#
  catalog-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./catalog-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
  order-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    expose:
      - 3001
    volumes:
      - ./order-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3001
  user-service:
    profiles:
      - litedev
      - dev
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    expose:
      - 3001
    volumes:
      - ./user-service:/workdir
      - /workdir/node_modules
    environment:
      NODE_ENV: development
      PORT: 3002
  
  #------------------------ KAFKA --------------------------#
  kafka-zookeeper:
    profiles:
      - dev
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    expose:
      - 2181
  kafka:
    profiles:
      - dev
    image: confluentinc/cp-kafka:latest
    depends_on: 
      - kafka-zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - 29092
  kafka-ui:
    profiles:
      - dev
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
      - kafka-zookeeper
    ports:
      - 9000:8080
    environment:
      # - KAFKA_CLUSTERS_0_NAME=local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181