FROM node:16-alpine3.11 AS builder
WORKDIR /workdir
COPY package*.json ./
RUN yarn install --frozen-lockfile
COPY . ./
RUN npm run build && npm prune --production

FROM node:16-alpine3.11
WORKDIR /workdir
ENV NODE_ENV=production
COPY --from=builder /workdir/dist ./dist
COPY --from=builder /workdir/node_modules ./node_modules
CMD ["node", "dist/main.js"]