// product
export const FETCH_PRODUCTS = 'FETCH_PRODUCT';

// categories
export const SET_CATEGORIES = 'SET_CATEGORIES';

// cart
export const SET_CART = 'SET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ITEM_CART = 'DETELE_ITEM_CART';
export const CHANGE_QUANTITY_ITEM_CART = 'CHANGE_QUANTITY_ITEM_CART';
export const DELETE_CART = 'DELETE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const SELECT_ITEM_CART = 'SELECT_ITEM_CART';
export const UNSELECT_ITEM_CART = 'UNSELECT_ITEM_CART';
export const SELECT_ALL_CART = 'SELECT_ALL_CART';
export const UNSELECT_ALL_CART = 'UNSELECT_ALL_CART';

// alert message
export const SHOW_ALERT_MESSAGE = 'SHOW_MESSAGE';
export const CLOSE_ALERT_MESSAGE = 'CLOSE MESSAGE';

// confim dialog
export const OPEN_CONFIRM_DIALOG = 'OPEN_CONFIRM_DIALOG';
export const CLOSE_CONFIRM_DIALOG = 'CLOSE_CONFIRM_DIALOG';

// fullscreen loading
export const OPEN_FULL_SCREEN_LOADING = 'OPEN_FULL_SCREEN_LOADING';
export const CLOSE_FULL_SCREEN_LOADING = 'CLOSE_FULL_SCREEN_LOADING';

// breadcrumbs

export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
export const SET_BREADCRUMBS_BY_STRING = 'SET_BREADCRUMBS_BY_STRING';
